"use client";

import { OBJECTION_DEFINITIONS, OUTCOME_DEFINITIONS, getOutcomeEvents } from "@/lib/outcomes";
import type { Lead, LeadFormValues } from "@/types/lead";
import { OutcomeLogger } from "@/components/leads/outcome-logger";

type CommercialFeedbackPanelProps = { lead: Lead; onChange: (values: Partial<LeadFormValues>) => void };
function formatCurrency(value?: number): string { return value === undefined ? "Sin estimar" : new Intl.NumberFormat("es-UY", { style: "currency", currency: "UYU", maximumFractionDigits: 0 }).format(value); }
function formatEventDate(value: string): string { return new Date(value).toLocaleString("es-AR", { year: "numeric", month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" }); }

export function CommercialFeedbackPanel({ lead, onChange }: CommercialFeedbackPanelProps) {
  const history = getOutcomeEvents(lead);
  return <section className="space-y-3 rounded-lg border border-zinc-200 bg-white p-4 dark:border-zinc-800 dark:bg-zinc-950"><div><h2 className="text-sm font-semibold uppercase tracking-wide text-zinc-500 dark:text-zinc-400">Outcome Logger</h2><p className="mt-1 text-xs text-zinc-500 dark:text-zinc-400">Registra llamadas y objeciones sin modificar pesos de scoring automáticamente.</p></div><dl className="grid gap-2 text-sm"><div className="flex justify-between gap-3"><dt className="text-zinc-500">Intentos</dt><dd>{lead.contactAttempts ?? 0}</dd></div><div className="flex justify-between gap-3"><dt className="text-zinc-500">Último outcome</dt><dd>{lead.lastOutcome ? OUTCOME_DEFINITIONS[lead.lastOutcome.outcome].label : "Sin resultado"}</dd></div><div className="flex justify-between gap-3"><dt className="text-zinc-500">Última objeción</dt><dd>{lead.lastObjection ? OBJECTION_DEFINITIONS[lead.lastObjection].label : "Sin objeción"}</dd></div><div className="flex justify-between gap-3"><dt className="text-zinc-500">Temperatura</dt><dd>{lead.commercialTemperature ?? "Sin dato"}</dd></div><div className="flex justify-between gap-3"><dt className="text-zinc-500">Próximo follow-up</dt><dd>{lead.nextFollowUpAt || "Sin fecha"}</dd></div><div className="flex justify-between gap-3"><dt className="text-zinc-500">Valor estimado</dt><dd>{formatCurrency(lead.estimatedDealValue ?? lead.dealValueEstimate)}</dd></div></dl><div className="border-t border-zinc-100 pt-3 dark:border-zinc-800"><OutcomeLogger lead={lead} onLeadChange={(nextLead) => onChange(nextLead)} /></div>{history.length ? <ol className="space-y-2 border-t border-zinc-100 pt-3 text-xs dark:border-zinc-800">{history.slice(0, 8).map((event) => <li key={event.id} className="rounded-md bg-zinc-50 p-2 dark:bg-zinc-900"><p className="font-medium text-zinc-800 dark:text-zinc-100">{OUTCOME_DEFINITIONS[event.outcome].label}{event.objection ? ` · ${OBJECTION_DEFINITIONS[event.objection].label}` : ""}</p><p className="text-zinc-500">{formatEventDate(event.occurredAt)}</p>{event.note ? <p className="mt-1 text-zinc-600 dark:text-zinc-300">{event.note}</p> : null}</li>)}</ol> : null}</section>;
}
